export const STRINGS = {
	title: "Piano MIDI Visualizer",
	activate: "Activer le MIDI",
	retry: "Réessayer",
	requesting: "Demande d'accès en cours…",
	noPiano: "Aucun piano",
	noPianoHelp: "Aucun piano détecté. Branchez votre piano MIDI et allumez-le.",
	pianoConnected: (names: string) => `Piano connecté : ${names}`,
	pianoUnplugged: "Piano débranché — rebranchez-le pour continuer",
	allPianos: "Tous les pianos",
	pianoChoice: "Piano à écouter",
	selectedUnplugged: (name: string) =>
		`${name} débranché — écoute de tous les pianos`,
	unsupported:
		"Votre navigateur ne gère pas le MIDI. Essayez Chrome, Edge ou Opera.",
	insecure:
		"Le MIDI exige une connexion sécurisée (HTTPS). Ouvrez cette page en HTTPS, avec Chrome, Edge ou Opera.",
	denied:
		"L'accès au MIDI a été refusé. Autorisez-le dans les réglages du site (icône à côté de l'adresse), puis rechargez la page.",
	error: "Impossible d'activer le MIDI. Vérifiez votre piano puis réessayez.",
	hintInactive: "Activez le MIDI, puis jouez une note",
	hintReady: "Jouez une note, elle apparaît ici",
	hintFrozen: "Historique figé. Reprenez le direct pour voir vos notes.",
	scoreLabel: "Partition",
	freeze: "Figer l'historique",
	resume: "Reprendre le direct",
	clear: "Effacer la partition",
	options: "Options",
	close: "Fermer",
	cleared: "Partition effacée",
	undo: "Annuler",
	noNotePlayed: "Aucune note jouée",
	chord: (notes: string) => `Accord : ${notes}`,
	describeCurrent: (notes: string) => `Accord en cours : ${notes}.`,
	describeNone: "Aucune note en cours.",
	describeRhythm: (signature: string, tempo: number) =>
		`Mesure ${signature}, tempo ${tempo}.`,
	describeHistoryEmpty: "Historique vide.",
	describeHistory: (count: number) =>
		`Historique : ${count} ${count === 1 ? "accord" : "accords"}.`,
	optionNames: "Noms de notes",
	optionNamesHelp: "Do, Ré, Mi…",
	optionFlats: "Bémols à la place des dièses",
	optionFlatsHelp: "Exemple : Sol♭ au lieu de Fa♯",
	optionAnnounce: "Annonce du dernier accord après un silence",
	optionAnnounceHelp: "Lue par votre lecteur d'écran",
	optionShortcuts: "Raccourcis clavier",
	optionShortcutsHelp:
		"F : figer · E : effacer · L : relire l'accord · M : métronome",
	rhythm: "Rythme",
	signatureLabel: "Mesure",
	tempoLabel: "Tempo (battements par minute)",
	tempoLess: "Ralentir",
	tempoMore: "Accélérer",
	optionMuted: "Couper le son du métronome",
	optionMutedHelp: "Le temps reste affiché à l'écran",
	metronomeStart: "Démarrer le métronome",
	metronomeStop: "Arrêter le métronome",
	metronomeStarted: "Métronome en marche",
	metronomeStartedSilent:
		"Métronome en marche, sans son : le navigateur n'a pas autorisé l'audio",
	metronomeStopped: "Métronome arrêté",
	signatureChanged: (signature: string) => `Mesure ${signature}`,
	tempoChanged: (tempo: number) => `Tempo ${tempo}`,
	tempoInvalid: "Tempo non valide : entrez un nombre entre 40 et 200",
	tempoClamped: (tempo: number) => `Tempo limité à ${tempo}`,
	soundMuted: "Son du métronome coupé",
	soundOn: "Son du métronome activé",
	on: "Activé",
	off: "Désactivé",
} as const;
